INSERT INTO words (word, category, difficulty) VALUES
-- Animals
('cat', 'Animals', 1), ('dog', 'Animals', 1), ('elephant', 'Animals', 2), ('giraffe', 'Animals', 2), ('penguin', 'Animals', 2), ('dolphin', 'Animals', 2), ('butterfly', 'Animals', 2), ('spider', 'Animals', 1), ('snake', 'Animals', 1), ('eagle', 'Animals', 2), ('whale', 'Animals', 2), ('lion', 'Animals', 1), ('tiger', 'Animals', 1), ('bear', 'Animals', 1), ('rabbit', 'Animals', 1), ('monkey', 'Animals', 1), ('horse', 'Animals', 1), ('chicken', 'Animals', 1), ('fish', 'Animals', 1), ('octopus', 'Animals', 2), ('kangaroo', 'Animals', 2), ('panda', 'Animals', 1), ('koala', 'Animals', 2), ('zebra', 'Animals', 2), ('crocodile', 'Animals', 3), ('frog', 'Animals', 1), ('turtle', 'Animals', 1), ('shark', 'Animals', 2), ('parrot', 'Animals', 2), ('owl', 'Animals', 2), ('bee', 'Animals', 1), ('ant', 'Animals', 1), ('crab', 'Animals', 2), ('jellyfish', 'Animals', 3), ('flamingo', 'Animals', 3), ('peacock', 'Animals', 3), ('camel', 'Animals', 2), ('gorilla', 'Animals', 2), ('deer', 'Animals', 2), ('wolf', 'Animals', 2),

-- Food
('pizza', 'Food', 1), ('hamburger', 'Food', 1), ('ice cream', 'Food', 1), ('spaghetti', 'Food', 2), ('sushi', 'Food', 2), ('taco', 'Food', 1), ('pancake', 'Food', 1), ('cookie', 'Food', 1), ('cake', 'Food', 1), ('donut', 'Food', 1), ('banana', 'Food', 1), ('apple', 'Food', 1), ('watermelon', 'Food', 2), ('popcorn', 'Food', 1), ('sandwich', 'Food', 1), ('hot dog', 'Food', 1), ('french fries', 'Food', 2), ('chocolate', 'Food', 1), ('cupcake', 'Food', 2), ('bread', 'Food', 1), ('cheese', 'Food', 1), ('egg', 'Food', 1), ('carrot', 'Food', 1), ('broccoli', 'Food', 2), ('mushroom', 'Food', 2), ('lemon', 'Food', 1), ('strawberry', 'Food', 2), ('grape', 'Food', 1), ('pineapple', 'Food', 2), ('corn', 'Food', 1), ('onion', 'Food', 1), ('tomato', 'Food', 1), ('pepper', 'Food', 1), ('rice', 'Food', 1), ('noodles', 'Food', 2), ('waffle', 'Food', 2), ('pretzel', 'Food', 3), ('burrito', 'Food', 2), ('salad', 'Food', 2), ('soup', 'Food', 1),

-- Objects
('umbrella', 'Objects', 2), ('telephone', 'Objects', 1), ('scissors', 'Objects', 2), ('glasses', 'Objects', 1), ('candle', 'Objects', 1), ('clock', 'Objects', 1), ('book', 'Objects', 1), ('chair', 'Objects', 1), ('lamp', 'Objects', 1), ('key', 'Objects', 1), ('mirror', 'Objects', 2), ('camera', 'Objects', 1), ('guitar', 'Objects', 2), ('bicycle', 'Objects', 2), ('balloon', 'Objects', 1), ('backpack', 'Objects', 2), ('pillow', 'Objects', 1), ('pencil', 'Objects', 1), ('brush', 'Objects', 1), ('hammer', 'Objects', 2), ('ladder', 'Objects', 2), ('trophy', 'Objects', 2), ('crown', 'Objects', 2), ('diamond', 'Objects', 2), ('treasure', 'Objects', 3), ('chest', 'Objects', 2), ('sword', 'Objects', 2), ('shield', 'Objects', 2), ('flag', 'Objects', 1), ('bell', 'Objects', 1), ('drum', 'Objects', 2), ('compass', 'Objects', 3), ('telescope', 'Objects', 3), ('binoculars', 'Objects', 3), ('magnifying glass', 'Objects', 3), ('envelope', 'Objects', 2), ('newspaper', 'Objects', 2), ('calendar', 'Objects', 2), ('wallet', 'Objects', 2), ('ring', 'Objects', 1),

-- Actions
('running', 'Actions', 1), ('dancing', 'Actions', 1), ('sleeping', 'Actions', 1), ('swimming', 'Actions', 1), ('flying', 'Actions', 1), ('climbing', 'Actions', 2), ('cooking', 'Actions', 1), ('painting', 'Actions', 1), ('singing', 'Actions', 1), ('reading', 'Actions', 1), ('jumping', 'Actions', 1), ('crying', 'Actions', 1), ('laughing', 'Actions', 1), ('eating', 'Actions', 1), ('drinking', 'Actions', 1), ('driving', 'Actions', 1), ('skiing', 'Actions', 2), ('surfing', 'Actions', 2), ('fishing', 'Actions', 1), ('camping', 'Actions', 2), ('gardening', 'Actions', 2), ('typing', 'Actions', 2), ('waving', 'Actions', 1), ('hugging', 'Actions', 1), ('fighting', 'Actions', 2), ('boxing', 'Actions', 2), ('wrestling', 'Actions', 3), ('diving', 'Actions', 2), ('skating', 'Actions', 2), ('bowling', 'Actions', 2), ('juggling', 'Actions', 3), ('knitting', 'Actions', 3), ('yawning', 'Actions', 2), ('sneezing', 'Actions', 2), ('whistling', 'Actions', 3),

-- Places
('beach', 'Places', 1), ('mountain', 'Places', 1), ('castle', 'Places', 2), ('hospital', 'Places', 2), ('school', 'Places', 1), ('library', 'Places', 2), ('museum', 'Places', 2), ('airport', 'Places', 2), ('restaurant', 'Places', 2), ('park', 'Places', 1), ('zoo', 'Places', 1), ('circus', 'Places', 2), ('farm', 'Places', 1), ('desert', 'Places', 2), ('island', 'Places', 2), ('volcano', 'Places', 2), ('waterfall', 'Places', 3), ('cave', 'Places', 2), ('bridge', 'Places', 2), ('lighthouse', 'Places', 3), ('stadium', 'Places', 2), ('theater', 'Places', 2), ('church', 'Places', 2), ('temple', 'Places', 2), ('pyramid', 'Places', 2), ('igloo', 'Places', 2), ('treehouse', 'Places', 2), ('skyscraper', 'Places', 3), ('factory', 'Places', 2), ('mall', 'Places', 1), ('garage', 'Places', 2), ('kitchen', 'Places', 1), ('bathroom', 'Places', 1), ('bedroom', 'Places', 1), ('garden', 'Places', 1),

-- Nature
('sun', 'Nature', 1), ('moon', 'Nature', 1), ('star', 'Nature', 1), ('cloud', 'Nature', 1), ('rainbow', 'Nature', 1), ('lightning', 'Nature', 2), ('tornado', 'Nature', 2), ('snowflake', 'Nature', 2), ('tree', 'Nature', 1), ('flower', 'Nature', 1), ('leaf', 'Nature', 1), ('river', 'Nature', 2), ('ocean', 'Nature', 2), ('forest', 'Nature', 2), ('cactus', 'Nature', 2), ('fire', 'Nature', 1), ('rain', 'Nature', 1), ('wind', 'Nature', 1), ('earth', 'Nature', 2), ('planet', 'Nature', 2), ('comet', 'Nature', 3), ('wave', 'Nature', 2), ('sunrise', 'Nature', 2), ('sunset', 'Nature', 2), ('iceberg', 'Nature', 3), ('coral', 'Nature', 3), ('avalanche', 'Nature', 3),

-- Sports
('soccer', 'Sports', 1), ('basketball', 'Sports', 1), ('tennis', 'Sports', 1), ('baseball', 'Sports', 1), ('football', 'Sports', 1), ('golf', 'Sports', 1), ('hockey', 'Sports', 2), ('volleyball', 'Sports', 2), ('gymnastics', 'Sports', 3), ('archery', 'Sports', 3), ('fencing', 'Sports', 3), ('rowing', 'Sports', 3), ('marathon', 'Sports', 2), ('skateboarding', 'Sports', 2), ('snowboarding', 'Sports', 2), ('cricket', 'Sports', 2), ('rugby', 'Sports', 2), ('badminton', 'Sports', 2), ('ping pong', 'Sports', 2), ('karate', 'Sports', 2), ('judo', 'Sports', 3), ('weightlifting', 'Sports', 2), ('cycling', 'Sports', 2), ('horse racing', 'Sports', 3), ('sailing', 'Sports', 2),

-- Technology
('robot', 'Technology', 1), ('rocket', 'Technology', 1), ('computer', 'Technology', 1), ('smartphone', 'Technology', 1), ('television', 'Technology', 1), ('headphones', 'Technology', 2), ('keyboard', 'Technology', 1), ('mouse', 'Technology', 1), ('printer', 'Technology', 2), ('drone', 'Technology', 2), ('satellite', 'Technology', 3), ('spaceship', 'Technology', 2), ('laser', 'Technology', 2), ('battery', 'Technology', 1), ('lightbulb', 'Technology', 1), ('microphone', 'Technology', 2), ('speaker', 'Technology', 1), ('webcam', 'Technology', 2), ('joystick', 'Technology', 2), ('console', 'Technology', 2), ('tablet', 'Technology', 1), ('watch', 'Technology', 1), ('calculator', 'Technology', 2), ('antenna', 'Technology', 2), ('router', 'Technology', 3), ('cable', 'Technology', 1), ('charger', 'Technology', 1), ('pixel', 'Technology', 3), ('hologram', 'Technology', 3), ('virtual reality', 'Technology', 3)
ON CONFLICT (word) DO NOTHING;
