import { WordChoice } from '../types.js';

export const WORDS_DATASET: WordChoice[] = [
  // --- Animals ---
  { word: 'cat', category: 'Animals', difficulty: 1 },
  { word: 'dog', category: 'Animals', difficulty: 1 },
  { word: 'fish', category: 'Animals', difficulty: 1 },
  { word: 'bird', category: 'Animals', difficulty: 1 },
  { word: 'duck', category: 'Animals', difficulty: 1 },
  { word: 'frog', category: 'Animals', difficulty: 1 },
  { word: 'bear', category: 'Animals', difficulty: 1 },
  { word: 'lion', category: 'Animals', difficulty: 1 },
  { word: 'tiger', category: 'Animals', difficulty: 1 },
  { word: 'rabbit', category: 'Animals', difficulty: 1 },
  { word: 'snake', category: 'Animals', difficulty: 1 },
  { word: 'spider', category: 'Animals', difficulty: 1 },
  { word: 'monkey', category: 'Animals', difficulty: 1 },
  { word: 'horse', category: 'Animals', difficulty: 1 },
  { word: 'cow', category: 'Animals', difficulty: 1 },
  { word: 'pig', category: 'Animals', difficulty: 1 },
  { word: 'sheep', category: 'Animals', difficulty: 1 },
  { word: 'chicken', category: 'Animals', difficulty: 1 },
  { word: 'ant', category: 'Animals', difficulty: 1 },
  { word: 'bee', category: 'Animals', difficulty: 1 },
  { word: 'butterfly', category: 'Animals', difficulty: 2 },
  { word: 'elephant', category: 'Animals', difficulty: 2 },
  { word: 'giraffe', category: 'Animals', difficulty: 2 },
  { word: 'penguin', category: 'Animals', difficulty: 2 },
  { word: 'dolphin', category: 'Animals', difficulty: 2 },
  { word: 'kangaroo', category: 'Animals', difficulty: 2 },
  { word: 'panda', category: 'Animals', difficulty: 2 },
  { word: 'zebra', category: 'Animals', difficulty: 2 },
  { word: 'octopus', category: 'Animals', difficulty: 2 },
  { word: 'turtle', category: 'Animals', difficulty: 2 },
  { word: 'shark', category: 'Animals', difficulty: 2 },
  { word: 'whale', category: 'Animals', difficulty: 2 },
  { word: 'eagle', category: 'Animals', difficulty: 2 },
  { word: 'owl', category: 'Animals', difficulty: 2 },
  { word: 'camel', category: 'Animals', difficulty: 2 },
  { word: 'deer', category: 'Animals', difficulty: 2 },
  { word: 'wolf', category: 'Animals', difficulty: 2 },
  { word: 'crab', category: 'Animals', difficulty: 2 },
  { word: 'snail', category: 'Animals', difficulty: 2 },
  { word: 'parrot', category: 'Animals', difficulty: 2 },
  { word: 'crocodile', category: 'Animals', difficulty: 3 },
  { word: 'chameleon', category: 'Animals', difficulty: 3 },
  { word: 'hedgehog', category: 'Animals', difficulty: 3 },
  { word: 'flamingo', category: 'Animals', difficulty: 3 },
  { word: 'peacock', category: 'Animals', difficulty: 3 },
  { word: 'jellyfish', category: 'Animals', difficulty: 3 },
  { word: 'gorilla', category: 'Animals', difficulty: 2 },
  { word: 'lobster', category: 'Animals', difficulty: 3 },

  // --- Food & Drinks ---
  { word: 'pizza', category: 'Food', difficulty: 1 },
  { word: 'hamburger', category: 'Food', difficulty: 1 },
  { word: 'apple', category: 'Food', difficulty: 1 },
  { word: 'banana', category: 'Food', difficulty: 1 },
  { word: 'cookie', category: 'Food', difficulty: 1 },
  { word: 'cake', category: 'Food', difficulty: 1 },
  { word: 'donut', category: 'Food', difficulty: 1 },
  { word: 'bread', category: 'Food', difficulty: 1 },
  { word: 'egg', category: 'Food', difficulty: 1 },
  { word: 'cheese', category: 'Food', difficulty: 1 },
  { word: 'ice cream', category: 'Food', difficulty: 1 },
  { word: 'popcorn', category: 'Food', difficulty: 1 },
  { word: 'hot dog', category: 'Food', difficulty: 1 },
  { word: 'taco', category: 'Food', difficulty: 1 },
  { word: 'carrot', category: 'Food', difficulty: 1 },
  { word: 'orange', category: 'Food', difficulty: 1 },
  { word: 'grapes', category: 'Food', difficulty: 1 },
  { word: 'lemon', category: 'Food', difficulty: 1 },
  { word: 'corn', category: 'Food', difficulty: 1 },
  { word: 'rice', category: 'Food', difficulty: 1 },
  { word: 'watermelon', category: 'Food', difficulty: 2 },
  { word: 'spaghetti', category: 'Food', difficulty: 2 },
  { word: 'sushi', category: 'Food', difficulty: 2 },
  { word: 'pancake', category: 'Food', difficulty: 2 },
  { word: 'sandwich', category: 'Food', difficulty: 2 },
  { word: 'french fries', category: 'Food', difficulty: 2 },
  { word: 'chocolate', category: 'Food', difficulty: 2 },
  { word: 'cupcake', category: 'Food', difficulty: 2 },
  { word: 'broccoli', category: 'Food', difficulty: 2 },
  { word: 'strawberry', category: 'Food', difficulty: 2 },
  { word: 'pineapple', category: 'Food', difficulty: 2 },
  { word: 'burrito', category: 'Food', difficulty: 2 },
  { word: 'waffle', category: 'Food', difficulty: 2 },
  { word: 'lollipop', category: 'Food', difficulty: 2 },
  { word: 'mushroom', category: 'Food', difficulty: 2 },
  { word: 'pretzel', category: 'Food', difficulty: 3 },
  { word: 'croissant', category: 'Food', difficulty: 3 },
  { word: 'avocado', category: 'Food', difficulty: 3 },
  { word: 'marshmallow', category: 'Food', difficulty: 3 },

  // --- Everyday Objects ---
  { word: 'pencil', category: 'Objects', difficulty: 1 },
  { word: 'book', category: 'Objects', difficulty: 1 },
  { word: 'chair', category: 'Objects', difficulty: 1 },
  { word: 'table', category: 'Objects', difficulty: 1 },
  { word: 'clock', category: 'Objects', difficulty: 1 },
  { word: 'key', category: 'Objects', difficulty: 1 },
  { word: 'cup', category: 'Objects', difficulty: 1 },
  { word: 'door', category: 'Objects', difficulty: 1 },
  { word: 'bed', category: 'Objects', difficulty: 1 },
  { word: 'lamp', category: 'Objects', difficulty: 1 },
  { word: 'hat', category: 'Objects', difficulty: 1 },
  { word: 'shoe', category: 'Objects', difficulty: 1 },
  { word: 'phone', category: 'Objects', difficulty: 1 },
  { word: 'window', category: 'Objects', difficulty: 1 },
  { word: 'bottle', category: 'Objects', difficulty: 1 },
  { word: 'bag', category: 'Objects', difficulty: 1 },
  { word: 'box', category: 'Objects', difficulty: 1 },
  { word: 'spoon', category: 'Objects', difficulty: 1 },
  { word: 'fork', category: 'Objects', difficulty: 1 },
  { word: 'plate', category: 'Objects', difficulty: 1 },
  { word: 'umbrella', category: 'Objects', difficulty: 2 },
  { word: 'scissors', category: 'Objects', difficulty: 2 },
  { word: 'glasses', category: 'Objects', difficulty: 2 },
  { word: 'candle', category: 'Objects', difficulty: 2 },
  { word: 'mirror', category: 'Objects', difficulty: 2 },
  { word: 'camera', category: 'Objects', difficulty: 2 },
  { word: 'guitar', category: 'Objects', difficulty: 2 },
  { word: 'bicycle', category: 'Objects', difficulty: 2 },
  { word: 'balloon', category: 'Objects', difficulty: 2 },
  { word: 'backpack', category: 'Objects', difficulty: 2 },
  { word: 'hammer', category: 'Objects', difficulty: 2 },
  { word: 'ladder', category: 'Objects', difficulty: 2 },
  { word: 'trophy', category: 'Objects', difficulty: 2 },
  { word: 'crown', category: 'Objects', difficulty: 2 },
  { word: 'diamond', category: 'Objects', difficulty: 2 },
  { word: 'sword', category: 'Objects', difficulty: 2 },
  { word: 'bell', category: 'Objects', difficulty: 2 },
  { word: 'drum', category: 'Objects', difficulty: 2 },
  { word: 'pillow', category: 'Objects', difficulty: 2 },
  { word: 'toilet', category: 'Objects', difficulty: 2 },
  { word: 'toothbrush', category: 'Objects', difficulty: 2 },
  { word: 'newspaper', category: 'Objects', difficulty: 2 },
  { word: 'telescope', category: 'Objects', difficulty: 3 },
  { word: 'compass', category: 'Objects', difficulty: 3 },
  { word: 'hourglass', category: 'Objects', difficulty: 3 },
  { word: 'parachute', category: 'Objects', difficulty: 3 },

  // --- Actions ---
  { word: 'running', category: 'Actions', difficulty: 1 },
  { word: 'jumping', category: 'Actions', difficulty: 1 },
  { word: 'sleeping', category: 'Actions', difficulty: 1 },
  { word: 'eating', category: 'Actions', difficulty: 1 },
  { word: 'drinking', category: 'Actions', difficulty: 1 },
  { word: 'crying', category: 'Actions', difficulty: 1 },
  { word: 'laughing', category: 'Actions', difficulty: 1 },
  { word: 'dancing', category: 'Actions', difficulty: 1 },
  { word: 'swimming', category: 'Actions', difficulty: 1 },
  { word: 'singing', category: 'Actions', difficulty: 1 },
  { word: 'flying', category: 'Actions', difficulty: 1 },
  { word: 'cooking', category: 'Actions', difficulty: 1 },
  { word: 'reading', category: 'Actions', difficulty: 1 },
  { word: 'painting', category: 'Actions', difficulty: 1 },
  { word: 'writing', category: 'Actions', difficulty: 1 },
  { word: 'walking', category: 'Actions', difficulty: 1 },
  { word: 'driving', category: 'Actions', difficulty: 2 },
  { word: 'climbing', category: 'Actions', difficulty: 2 },
  { word: 'fishing', category: 'Actions', difficulty: 2 },
  { word: 'skiing', category: 'Actions', difficulty: 2 },
  { word: 'surfing', category: 'Actions', difficulty: 2 },
  { word: 'skating', category: 'Actions', difficulty: 2 },
  { word: 'camping', category: 'Actions', difficulty: 2 },
  { word: 'gardening', category: 'Actions', difficulty: 2 },
  { word: 'hugging', category: 'Actions', difficulty: 2 },
  { word: 'waving', category: 'Actions', difficulty: 2 },
  { word: 'skateboarding', category: 'Actions', difficulty: 2 },
  { word: 'juggling', category: 'Actions', difficulty: 3 },
  { word: 'knitting', category: 'Actions', difficulty: 3 },
  { word: 'sneezing', category: 'Actions', difficulty: 3 },
  { word: 'yawning', category: 'Actions', difficulty: 3 },

  // --- Nature ---
  { word: 'sun', category: 'Nature', difficulty: 1 },
  { word: 'moon', category: 'Nature', difficulty: 1 },
  { word: 'star', category: 'Nature', difficulty: 1 },
  { word: 'tree', category: 'Nature', difficulty: 1 },
  { word: 'flower', category: 'Nature', difficulty: 1 },
  { word: 'rain', category: 'Nature', difficulty: 1 },
  { word: 'cloud', category: 'Nature', difficulty: 1 },
  { word: 'fire', category: 'Nature', difficulty: 1 },
  { word: 'water', category: 'Nature', difficulty: 1 },
  { word: 'rainbow', category: 'Nature', difficulty: 1 },
  { word: 'snow', category: 'Nature', difficulty: 1 },
  { word: 'leaf', category: 'Nature', difficulty: 1 },
  { word: 'grass', category: 'Nature', difficulty: 1 },
  { word: 'mountain', category: 'Nature', difficulty: 2 },
  { word: 'ocean', category: 'Nature', difficulty: 2 },
  { word: 'river', category: 'Nature', difficulty: 2 },
  { word: 'forest', category: 'Nature', difficulty: 2 },
  { word: 'volcano', category: 'Nature', difficulty: 2 },
  { word: 'lightning', category: 'Nature', difficulty: 2 },
  { word: 'tornado', category: 'Nature', difficulty: 2 },
  { word: 'snowflake', category: 'Nature', difficulty: 2 },
  { word: 'cactus', category: 'Nature', difficulty: 2 },
  { word: 'sunrise', category: 'Nature', difficulty: 2 },
  { word: 'sunset', category: 'Nature', difficulty: 2 },
  { word: 'waterfall', category: 'Nature', difficulty: 3 },
  { word: 'iceberg', category: 'Nature', difficulty: 3 },
  { word: 'eclipse', category: 'Nature', difficulty: 3 },

  // --- Vehicles & Transport ---
  { word: 'car', category: 'Transport', difficulty: 1 },
  { word: 'bus', category: 'Transport', difficulty: 1 },
  { word: 'train', category: 'Transport', difficulty: 1 },
  { word: 'boat', category: 'Transport', difficulty: 1 },
  { word: 'airplane', category: 'Transport', difficulty: 1 },
  { word: 'truck', category: 'Transport', difficulty: 1 },
  { word: 'motorcycle', category: 'Transport', difficulty: 2 },
  { word: 'helicopter', category: 'Transport', difficulty: 2 },
  { word: 'submarine', category: 'Transport', difficulty: 2 },
  { word: 'rocket', category: 'Transport', difficulty: 2 },
  { word: 'skateboard', category: 'Transport', difficulty: 2 },
  { word: 'ambulance', category: 'Transport', difficulty: 2 },
  { word: 'fire truck', category: 'Transport', difficulty: 2 },
  { word: 'sailboat', category: 'Transport', difficulty: 2 },
  { word: 'hot air balloon', category: 'Transport', difficulty: 3 },
  { word: 'spaceship', category: 'Transport', difficulty: 3 },

  // --- Places ---
  { word: 'house', category: 'Places', difficulty: 1 },
  { word: 'school', category: 'Places', difficulty: 1 },
  { word: 'park', category: 'Places', difficulty: 1 },
  { word: 'beach', category: 'Places', difficulty: 1 },
  { word: 'hospital', category: 'Places', difficulty: 2 },
  { word: 'castle', category: 'Places', difficulty: 2 },
  { word: 'airport', category: 'Places', difficulty: 2 },
  { word: 'restaurant', category: 'Places', difficulty: 2 },
  { word: 'museum', category: 'Places', difficulty: 2 },
  { word: 'library', category: 'Places', difficulty: 2 },
  { word: 'zoo', category: 'Places', difficulty: 2 },
  { word: 'farm', category: 'Places', difficulty: 2 },
  { word: 'island', category: 'Places', difficulty: 2 },
  { word: 'desert', category: 'Places', difficulty: 2 },
  { word: 'church', category: 'Places', difficulty: 2 },
  { word: 'stadium', category: 'Places', difficulty: 2 },
  { word: 'bridge', category: 'Places', difficulty: 2 },
  { word: 'lighthouse', category: 'Places', difficulty: 3 },
  { word: 'pyramid', category: 'Places', difficulty: 2 },
  { word: 'igloo', category: 'Places', difficulty: 2 },
  { word: 'treehouse', category: 'Places', difficulty: 3 },

  // --- People & Body ---
  { word: 'baby', category: 'People', difficulty: 1 },
  { word: 'doctor', category: 'People', difficulty: 1 },
  { word: 'teacher', category: 'People', difficulty: 1 },
  { word: 'police', category: 'People', difficulty: 1 },
  { word: 'king', category: 'People', difficulty: 1 },
  { word: 'queen', category: 'People', difficulty: 1 },
  { word: 'ninja', category: 'People', difficulty: 2 },
  { word: 'pirate', category: 'People', difficulty: 2 },
  { word: 'clown', category: 'People', difficulty: 2 },
  { word: 'astronaut', category: 'People', difficulty: 2 },
  { word: 'superhero', category: 'People', difficulty: 2 },
  { word: 'wizard', category: 'People', difficulty: 2 },
  { word: 'angel', category: 'People', difficulty: 2 },
  { word: 'robot', category: 'People', difficulty: 2 },
  { word: 'ghost', category: 'People', difficulty: 1 },
  { word: 'mermaid', category: 'People', difficulty: 3 },

  // --- Sports & Games ---
  { word: 'soccer', category: 'Sports', difficulty: 1 },
  { word: 'basketball', category: 'Sports', difficulty: 1 },
  { word: 'tennis', category: 'Sports', difficulty: 1 },
  { word: 'baseball', category: 'Sports', difficulty: 1 },
  { word: 'football', category: 'Sports', difficulty: 1 },
  { word: 'bowling', category: 'Sports', difficulty: 2 },
  { word: 'golf', category: 'Sports', difficulty: 2 },
  { word: 'hockey', category: 'Sports', difficulty: 2 },
  { word: 'boxing', category: 'Sports', difficulty: 2 },
  { word: 'archery', category: 'Sports', difficulty: 2 },
  { word: 'ping pong', category: 'Sports', difficulty: 2 },
  { word: 'chess', category: 'Sports', difficulty: 2 },
  { word: 'karate', category: 'Sports', difficulty: 2 },
  { word: 'volleyball', category: 'Sports', difficulty: 2 },
  { word: 'cricket', category: 'Sports', difficulty: 2 },
  { word: 'gymnastics', category: 'Sports', difficulty: 3 },
  { word: 'fencing', category: 'Sports', difficulty: 3 },
  { word: 'snowboarding', category: 'Sports', difficulty: 3 },

  // --- Technology ---
  { word: 'computer', category: 'Technology', difficulty: 1 },
  { word: 'television', category: 'Technology', difficulty: 1 },
  { word: 'battery', category: 'Technology', difficulty: 1 },
  { word: 'lightbulb', category: 'Technology', difficulty: 1 },
  { word: 'keyboard', category: 'Technology', difficulty: 2 },
  { word: 'headphones', category: 'Technology', difficulty: 2 },
  { word: 'drone', category: 'Technology', difficulty: 2 },
  { word: 'satellite', category: 'Technology', difficulty: 2 },
  { word: 'microphone', category: 'Technology', difficulty: 2 },
  { word: 'printer', category: 'Technology', difficulty: 2 },
  { word: 'joystick', category: 'Technology', difficulty: 2 },
  { word: 'solar panel', category: 'Technology', difficulty: 3 },
  { word: 'wifi', category: 'Technology', difficulty: 2 },

  // --- Clothing ---
  { word: 'shirt', category: 'Clothing', difficulty: 1 },
  { word: 'pants', category: 'Clothing', difficulty: 1 },
  { word: 'dress', category: 'Clothing', difficulty: 1 },
  { word: 'socks', category: 'Clothing', difficulty: 1 },
  { word: 'gloves', category: 'Clothing', difficulty: 1 },
  { word: 'scarf', category: 'Clothing', difficulty: 2 },
  { word: 'tie', category: 'Clothing', difficulty: 2 },
  { word: 'belt', category: 'Clothing', difficulty: 2 },
  { word: 'necklace', category: 'Clothing', difficulty: 2 },
  { word: 'ring', category: 'Clothing', difficulty: 1 },
  { word: 'sunglasses', category: 'Clothing', difficulty: 2 },
  { word: 'boots', category: 'Clothing', difficulty: 2 },
  { word: 'helmet', category: 'Clothing', difficulty: 2 },

  // --- Household ---
  { word: 'television', category: 'Household', difficulty: 1 },
  { word: 'fridge', category: 'Household', difficulty: 1 },
  { word: 'oven', category: 'Household', difficulty: 1 },
  { word: 'bathtub', category: 'Household', difficulty: 2 },
  { word: 'shower', category: 'Household', difficulty: 2 },
  { word: 'sofa', category: 'Household', difficulty: 1 },
  { word: 'stairs', category: 'Household', difficulty: 2 },
  { word: 'fence', category: 'Household', difficulty: 2 },
  { word: 'chimney', category: 'Household', difficulty: 2 },
  { word: 'mailbox', category: 'Household', difficulty: 2 },
  { word: 'broom', category: 'Household', difficulty: 2 },
  { word: 'vacuum', category: 'Household', difficulty: 3 },
  { word: 'calendar', category: 'Household', difficulty: 2 },
  { word: 'alarm clock', category: 'Household', difficulty: 2 },

  // --- Miscellaneous (General & Useful) ---
  { word: 'heart', category: 'General', difficulty: 1 },
  { word: 'flag', category: 'General', difficulty: 1 },
  { word: 'money', category: 'General', difficulty: 1 },
  { word: 'map', category: 'General', difficulty: 1 },
  { word: 'music', category: 'General', difficulty: 1 },
  { word: 'smile', category: 'General', difficulty: 1 },
  { word: 'birthday cake', category: 'General', difficulty: 2 },
  { word: 'snowman', category: 'General', difficulty: 1 },
  { word: 'kite', category: 'General', difficulty: 1 },
  { word: 'treasure', category: 'General', difficulty: 2 },
  { word: 'gift', category: 'General', difficulty: 1 },
  { word: 'candle', category: 'General', difficulty: 1 },
  { word: 'arrow', category: 'General', difficulty: 1 },
  { word: 'anchor', category: 'General', difficulty: 2 },
  { word: 'bone', category: 'General', difficulty: 1 },
  { word: 'planet', category: 'General', difficulty: 2 },
  { word: 'earth', category: 'General', difficulty: 2 },
  { word: 'tent', category: 'General', difficulty: 2 },
  { word: 'campfire', category: 'General', difficulty: 2 },
  { word: 'fingerprint', category: 'General', difficulty: 3 },
  { word: 'puzzle', category: 'General', difficulty: 2 },
  { word: 'dice', category: 'General', difficulty: 2 },
  { word: 'trophy', category: 'General', difficulty: 2 },
  { word: 'medal', category: 'General', difficulty: 2 },
  { word: 'magnifying glass', category: 'General', difficulty: 3 },
  { word: 'envelope', category: 'General', difficulty: 2 },
  { word: 'stamp', category: 'General', difficulty: 2 },
  { word: 'ticket', category: 'General', difficulty: 2 },
  { word: 'drum', category: 'General', difficulty: 2 },
  { word: 'piano', category: 'General', difficulty: 2 },
  { word: 'violin', category: 'General', difficulty: 3 },
  { word: 'trumpet', category: 'General', difficulty: 3 },
];
