import { WordChoice } from '../types.js';

export const WORDS_DATASET: WordChoice[] = [
  // ==========================================
  // --- 1. Maps & Landmarks (World & Geography) ---
  // ==========================================
  { word: 'world map', category: 'Maps', difficulty: 1 },
  { word: 'compass', category: 'Maps', difficulty: 1 },
  { word: 'globe', category: 'Maps', difficulty: 1 },
  { word: 'island', category: 'Maps', difficulty: 1 },
  { word: 'mountain', category: 'Maps', difficulty: 1 },
  { word: 'river', category: 'Maps', difficulty: 1 },
  { word: 'volcano', category: 'Maps', difficulty: 1 },
  { word: 'ocean', category: 'Maps', difficulty: 1 },
  { word: 'desert', category: 'Maps', difficulty: 1 },
  { word: 'treasure map', category: 'Maps', difficulty: 2 },
  { word: 'pyramid', category: 'Maps', difficulty: 2 },
  { word: 'eiffel tower', category: 'Maps', difficulty: 2 },
  { word: 'statue of liberty', category: 'Maps', difficulty: 2 },
  { word: 'big ben', category: 'Maps', difficulty: 2 },
  { word: 'taj mahal', category: 'Maps', difficulty: 2 },
  { word: 'mount everest', category: 'Maps', difficulty: 2 },
  { word: 'colosseum', category: 'Maps', difficulty: 2 },
  { word: 'great wall', category: 'Maps', difficulty: 2 },
  { word: 'volcano island', category: 'Maps', difficulty: 2 },
  { word: 'north pole', category: 'Maps', difficulty: 2 },
  { word: 'south pole', category: 'Maps', difficulty: 2 },
  { word: 'subway map', category: 'Maps', difficulty: 2 },
  { word: 'gps navigation', category: 'Maps', difficulty: 2 },
  { word: 'lighthouse', category: 'Maps', difficulty: 2 },
  { word: 'waterfall', category: 'Maps', difficulty: 2 },
  { word: 'canyon', category: 'Maps', difficulty: 2 },
  { word: 'cave', category: 'Maps', difficulty: 2 },
  { word: 'coral reef', category: 'Maps', difficulty: 2 },
  { word: 'equator', category: 'Maps', difficulty: 3 },
  { word: 'continent', category: 'Maps', difficulty: 3 },
  { word: 'compass rose', category: 'Maps', difficulty: 3 },
  { word: 'atlas', category: 'Maps', difficulty: 3 },
  { word: 'grand canyon', category: 'Maps', difficulty: 3 },
  { word: 'bermuda triangle', category: 'Maps', difficulty: 3 },
  { word: 'leaning tower of pisa', category: 'Maps', difficulty: 3 },
  { word: 'golden gate bridge', category: 'Maps', difficulty: 3 },
  { word: 'sydney opera house', category: 'Maps', difficulty: 3 },
  { word: 'mount fuji', category: 'Maps', difficulty: 3 },
  { word: 'stonehenge', category: 'Maps', difficulty: 3 },
  { word: 'amazon river', category: 'Maps', difficulty: 3 },
  { word: 'sahara desert', category: 'Maps', difficulty: 3 },
  { word: 'time zone', category: 'Maps', difficulty: 3 },

  // ==========================================
  // --- 2. Fruits (Delicious & Colorful) ---
  // ==========================================
  { word: 'apple', category: 'Fruits', difficulty: 1 },
  { word: 'banana', category: 'Fruits', difficulty: 1 },
  { word: 'orange', category: 'Fruits', difficulty: 1 },
  { word: 'grapes', category: 'Fruits', difficulty: 1 },
  { word: 'lemon', category: 'Fruits', difficulty: 1 },
  { word: 'watermelon', category: 'Fruits', difficulty: 1 },
  { word: 'strawberry', category: 'Fruits', difficulty: 1 },
  { word: 'mango', category: 'Fruits', difficulty: 1 },
  { word: 'lime', category: 'Fruits', difficulty: 1 },
  { word: 'pear', category: 'Fruits', difficulty: 1 },
  { word: 'peach', category: 'Fruits', difficulty: 2 },
  { word: 'cherry', category: 'Fruits', difficulty: 2 },
  { word: 'pineapple', category: 'Fruits', difficulty: 2 },
  { word: 'coconut', category: 'Fruits', difficulty: 2 },
  { word: 'blueberry', category: 'Fruits', difficulty: 2 },
  { word: 'kiwi', category: 'Fruits', difficulty: 2 },
  { word: 'avocado', category: 'Fruits', difficulty: 2 },
  { word: 'papaya', category: 'Fruits', difficulty: 2 },
  { word: 'plum', category: 'Fruits', difficulty: 2 },
  { word: 'apricot', category: 'Fruits', difficulty: 2 },
  { word: 'guava', category: 'Fruits', difficulty: 2 },
  { word: 'cantaloupe', category: 'Fruits', difficulty: 2 },
  { word: 'dragonfruit', category: 'Fruits', difficulty: 3 },
  { word: 'pomegranate', category: 'Fruits', difficulty: 3 },
  { word: 'raspberry', category: 'Fruits', difficulty: 3 },
  { word: 'blackberry', category: 'Fruits', difficulty: 3 },
  { word: 'fig', category: 'Fruits', difficulty: 3 },
  { word: 'passion fruit', category: 'Fruits', difficulty: 3 },
  { word: 'starfruit', category: 'Fruits', difficulty: 3 },
  { word: 'grapefruit', category: 'Fruits', difficulty: 3 },
  { word: 'durian', category: 'Fruits', difficulty: 3 },
  { word: 'lychee', category: 'Fruits', difficulty: 3 },
  { word: 'cranberry', category: 'Fruits', difficulty: 3 },
  { word: 'tangerine', category: 'Fruits', difficulty: 2 },

  // ==========================================
  // --- 3. Vegetables (Farm & Garden) ---
  // ==========================================
  { word: 'carrot', category: 'Vegetables', difficulty: 1 },
  { word: 'corn', category: 'Vegetables', difficulty: 1 },
  { word: 'potato', category: 'Vegetables', difficulty: 1 },
  { word: 'onion', category: 'Vegetables', difficulty: 1 },
  { word: 'tomato', category: 'Vegetables', difficulty: 1 },
  { word: 'cucumber', category: 'Vegetables', difficulty: 1 },
  { word: 'mushroom', category: 'Vegetables', difficulty: 1 },
  { word: 'peas', category: 'Vegetables', difficulty: 1 },
  { word: 'broccoli', category: 'Vegetables', difficulty: 2 },
  { word: 'pumpkin', category: 'Vegetables', difficulty: 2 },
  { word: 'chili pepper', category: 'Vegetables', difficulty: 2 },
  { word: 'eggplant', category: 'Vegetables', difficulty: 2 },
  { word: 'garlic', category: 'Vegetables', difficulty: 2 },
  { word: 'cabbage', category: 'Vegetables', difficulty: 2 },
  { word: 'spinach', category: 'Vegetables', difficulty: 2 },
  { word: 'bell pepper', category: 'Vegetables', difficulty: 2 },
  { word: 'radish', category: 'Vegetables', difficulty: 2 },
  { word: 'lettuce', category: 'Vegetables', difficulty: 2 },
  { word: 'celery', category: 'Vegetables', difficulty: 2 },
  { word: 'sweet potato', category: 'Vegetables', difficulty: 2 },
  { word: 'ginger', category: 'Vegetables', difficulty: 2 },
  { word: 'cauliflower', category: 'Vegetables', difficulty: 3 },
  { word: 'beetroot', category: 'Vegetables', difficulty: 3 },
  { word: 'zucchini', category: 'Vegetables', difficulty: 3 },
  { word: 'artichoke', category: 'Vegetables', difficulty: 3 },
  { word: 'asparagus', category: 'Vegetables', difficulty: 3 },
  { word: 'brussels sprouts', category: 'Vegetables', difficulty: 3 },
  { word: 'leek', category: 'Vegetables', difficulty: 3 },
  { word: 'kale', category: 'Vegetables', difficulty: 3 },
  { word: 'turnip', category: 'Vegetables', difficulty: 3 },
  { word: 'butternut squash', category: 'Vegetables', difficulty: 3 },

  // ==========================================
  // --- 4. Cars & Vehicles (Fast & Powerful) ---
  // ==========================================
  { word: 'car', category: 'Cars', difficulty: 1 },
  { word: 'bus', category: 'Cars', difficulty: 1 },
  { word: 'train', category: 'Cars', difficulty: 1 },
  { word: 'truck', category: 'Cars', difficulty: 1 },
  { word: 'bicycle', category: 'Cars', difficulty: 1 },
  { word: 'boat', category: 'Cars', difficulty: 1 },
  { word: 'airplane', category: 'Cars', difficulty: 1 },
  { word: 'van', category: 'Cars', difficulty: 1 },
  { word: 'sports car', category: 'Cars', difficulty: 2 },
  { word: 'police car', category: 'Cars', difficulty: 2 },
  { word: 'fire truck', category: 'Cars', difficulty: 2 },
  { word: 'ambulance', category: 'Cars', difficulty: 2 },
  { word: 'motorcycle', category: 'Cars', difficulty: 2 },
  { word: 'monster truck', category: 'Cars', difficulty: 2 },
  { word: 'formula 1', category: 'Cars', difficulty: 2 },
  { word: 'limousine', category: 'Cars', difficulty: 2 },
  { word: 'tractor', category: 'Cars', difficulty: 2 },
  { word: 'bulldozer', category: 'Cars', difficulty: 2 },
  { word: 'submarine', category: 'Cars', difficulty: 2 },
  { word: 'helicopter', category: 'Cars', difficulty: 2 },
  { word: 'skateboard', category: 'Cars', difficulty: 2 },
  { word: 'scooter', category: 'Cars', difficulty: 2 },
  { word: 'go-kart', category: 'Cars', difficulty: 2 },
  { word: 'tank', category: 'Cars', difficulty: 2 },
  { word: 'jet ski', category: 'Cars', difficulty: 2 },
  { word: 'spaceship', category: 'Cars', difficulty: 2 },
  { word: 'taxi', category: 'Cars', difficulty: 2 },
  { word: 'garbage truck', category: 'Cars', difficulty: 2 },
  { word: 'snowmobile', category: 'Cars', difficulty: 2 },
  { word: 'roller skates', category: 'Cars', difficulty: 2 },
  { word: 'hovercraft', category: 'Cars', difficulty: 3 },
  { word: 'forklift', category: 'Cars', difficulty: 3 },
  { word: 'cable car', category: 'Cars', difficulty: 3 },
  { word: 'hot air balloon', category: 'Cars', difficulty: 3 },
  { word: 'steam locomotive', category: 'Cars', difficulty: 3 },
  { word: 'lunar rover', category: 'Cars', difficulty: 3 },
  { word: 'battleship', category: 'Cars', difficulty: 3 },
  { word: 'zeppelin', category: 'Cars', difficulty: 3 },
  { word: 'glider', category: 'Cars', difficulty: 3 },
  { word: 'rickshaw', category: 'Cars', difficulty: 3 },

  // ==========================================
  // --- 5. Symbols & Logos (Universal Signs) ---
  // ==========================================
  { word: 'heart', category: 'Symbols', difficulty: 1 },
  { word: 'star', category: 'Symbols', difficulty: 1 },
  { word: 'smiley face', category: 'Symbols', difficulty: 1 },
  { word: 'checkmark', category: 'Symbols', difficulty: 1 },
  { word: 'cross', category: 'Symbols', difficulty: 1 },
  { word: 'arrow', category: 'Symbols', difficulty: 1 },
  { word: 'question mark', category: 'Symbols', difficulty: 1 },
  { word: 'exclamation mark', category: 'Symbols', difficulty: 1 },
  { word: 'dollar sign', category: 'Symbols', difficulty: 1 },
  { word: 'hash sign', category: 'Symbols', difficulty: 1 },
  { word: 'peace sign', category: 'Symbols', difficulty: 2 },
  { word: 'yin yang', category: 'Symbols', difficulty: 2 },
  { word: 'wifi', category: 'Symbols', difficulty: 2 },
  { word: 'recycle symbol', category: 'Symbols', difficulty: 2 },
  { word: 'lightning bolt', category: 'Symbols', difficulty: 2 },
  { word: 'infinity', category: 'Symbols', difficulty: 2 },
  { word: 'target', category: 'Symbols', difficulty: 2 },
  { word: 'anchor', category: 'Symbols', difficulty: 2 },
  { word: 'music note', category: 'Symbols', difficulty: 2 },
  { word: 'crescent moon', category: 'Symbols', difficulty: 2 },
  { word: 'sun symbol', category: 'Symbols', difficulty: 2 },
  { word: 'skull and crossbones', category: 'Symbols', difficulty: 2 },
  { word: 'heart with arrow', category: 'Symbols', difficulty: 2 },
  { word: 'four leaf clover', category: 'Symbols', difficulty: 2 },
  { word: 'crown icon', category: 'Symbols', difficulty: 2 },
  { word: 'shield icon', category: 'Symbols', difficulty: 2 },
  { word: 'biohazard', category: 'Symbols', difficulty: 3 },
  { word: 'radiation', category: 'Symbols', difficulty: 3 },
  { word: 'prohibited sign', category: 'Symbols', difficulty: 3 },
  { word: 'euro sign', category: 'Symbols', difficulty: 3 },
  { word: 'pound sign', category: 'Symbols', difficulty: 3 },
  { word: 'bitcoin logo', category: 'Symbols', difficulty: 3 },
  { word: 'pi symbol', category: 'Symbols', difficulty: 3 },
  { word: 'omega symbol', category: 'Symbols', difficulty: 3 },
  { word: 'bluetooth logo', category: 'Symbols', difficulty: 3 },
  { word: 'battery icon', category: 'Symbols', difficulty: 2 },
  { word: 'play button', category: 'Symbols', difficulty: 1 },
  { word: 'pause button', category: 'Symbols', difficulty: 1 },

  // ==========================================
  // --- 6. Pop Culture, Superheroes & Gaming ---
  // ==========================================
  { word: 'batman', category: 'Pop Culture', difficulty: 1 },
  { word: 'superman', category: 'Pop Culture', difficulty: 1 },
  { word: 'spider-man', category: 'Pop Culture', difficulty: 1 },
  { word: 'pikachu', category: 'Pop Culture', difficulty: 1 },
  { word: 'mario', category: 'Pop Culture', difficulty: 1 },
  { word: 'luigi', category: 'Pop Culture', difficulty: 1 },
  { word: 'spongebob', category: 'Pop Culture', difficulty: 1 },
  { word: 'patrick star', category: 'Pop Culture', difficulty: 1 },
  { word: 'mickey mouse', category: 'Pop Culture', difficulty: 1 },
  { word: 'pac-man', category: 'Pop Culture', difficulty: 1 },
  { word: 'sonic the hedgehog', category: 'Pop Culture', difficulty: 2 },
  { word: 'iron man', category: 'Pop Culture', difficulty: 2 },
  { word: 'yoda', category: 'Pop Culture', difficulty: 2 },
  { word: 'harry potter', category: 'Pop Culture', difficulty: 2 },
  { word: 'naruto', category: 'Pop Culture', difficulty: 2 },
  { word: 'shrek', category: 'Pop Culture', difficulty: 2 },
  { word: 'elsa', category: 'Pop Culture', difficulty: 2 },
  { word: 'hulk', category: 'Pop Culture', difficulty: 2 },
  { word: 'minion', category: 'Pop Culture', difficulty: 2 },
  { word: 'thor', category: 'Pop Culture', difficulty: 2 },
  { word: 'captain america', category: 'Pop Culture', difficulty: 2 },
  { word: 'deadpool', category: 'Pop Culture', difficulty: 2 },
  { word: 'darth vader', category: 'Pop Culture', difficulty: 2 },
  { word: 'goku', category: 'Pop Culture', difficulty: 2 },
  { word: 'scooby doo', category: 'Pop Culture', difficulty: 2 },
  { word: 'buzz lightyear', category: 'Pop Culture', difficulty: 2 },
  { word: 'sheriff woody', category: 'Pop Culture', difficulty: 2 },
  { word: 'wolverine', category: 'Pop Culture', difficulty: 3 },
  { word: 'minecraft steve', category: 'Pop Culture', difficulty: 3 },
  { word: 'zelda', category: 'Pop Culture', difficulty: 3 },
  { word: 'thanos', category: 'Pop Culture', difficulty: 3 },
  { word: 'joker', category: 'Pop Culture', difficulty: 2 },
  { word: 'wonder woman', category: 'Pop Culture', difficulty: 2 },
  { word: 'black panther', category: 'Pop Culture', difficulty: 2 },
  { word: 'optimus prime', category: 'Pop Culture', difficulty: 3 },
  { word: 'godzilla', category: 'Pop Culture', difficulty: 2 },
  { word: 'king kong', category: 'Pop Culture', difficulty: 2 },
  { word: 'lara croft', category: 'Pop Culture', difficulty: 3 },

  // ==========================================
  // --- 7. Fun Animals & Wildlife ---
  // ==========================================
  { word: 'cat', category: 'Animals', difficulty: 1 },
  { word: 'dog', category: 'Animals', difficulty: 1 },
  { word: 'duck', category: 'Animals', difficulty: 1 },
  { word: 'lion', category: 'Animals', difficulty: 1 },
  { word: 'tiger', category: 'Animals', difficulty: 1 },
  { word: 'bear', category: 'Animals', difficulty: 1 },
  { word: 'rabbit', category: 'Animals', difficulty: 1 },
  { word: 'monkey', category: 'Animals', difficulty: 1 },
  { word: 'pig', category: 'Animals', difficulty: 1 },
  { word: 'cow', category: 'Animals', difficulty: 1 },
  { word: 'horse', category: 'Animals', difficulty: 1 },
  { word: 'sheep', category: 'Animals', difficulty: 1 },
  { word: 'frog', category: 'Animals', difficulty: 1 },
  { word: 'snake', category: 'Animals', difficulty: 1 },
  { word: 'chicken', category: 'Animals', difficulty: 1 },
  { word: 'penguin', category: 'Animals', difficulty: 2 },
  { word: 'dolphin', category: 'Animals', difficulty: 2 },
  { word: 'elephant', category: 'Animals', difficulty: 2 },
  { word: 'giraffe', category: 'Animals', difficulty: 2 },
  { word: 'kangaroo', category: 'Animals', difficulty: 2 },
  { word: 'panda', category: 'Animals', difficulty: 2 },
  { word: 'zebra', category: 'Animals', difficulty: 2 },
  { word: 'octopus', category: 'Animals', difficulty: 2 },
  { word: 'shark', category: 'Animals', difficulty: 2 },
  { word: 'whale', category: 'Animals', difficulty: 2 },
  { word: 'koala', category: 'Animals', difficulty: 2 },
  { word: 'hamster', category: 'Animals', difficulty: 2 },
  { word: 'flamingo', category: 'Animals', difficulty: 2 },
  { word: 'sloth', category: 'Animals', difficulty: 2 },
  { word: 'gorilla', category: 'Animals', difficulty: 2 },
  { word: 'wolf', category: 'Animals', difficulty: 2 },
  { word: 'fox', category: 'Animals', difficulty: 2 },
  { word: 'owl', category: 'Animals', difficulty: 2 },
  { word: 'eagle', category: 'Animals', difficulty: 2 },
  { word: 'bat', category: 'Animals', difficulty: 2 },
  { word: 'parrot', category: 'Animals', difficulty: 2 },
  { word: 'squirrel', category: 'Animals', difficulty: 2 },
  { word: 'deer', category: 'Animals', difficulty: 2 },
  { word: 'crocodile', category: 'Animals', difficulty: 2 },
  { word: 'turtle', category: 'Animals', difficulty: 2 },
  { word: 'chameleon', category: 'Animals', difficulty: 3 },
  { word: 'platypus', category: 'Animals', difficulty: 3 },
  { word: 't-rex', category: 'Animals', difficulty: 2 },
  { word: 'narwhal', category: 'Animals', difficulty: 3 },
  { word: 'llama', category: 'Animals', difficulty: 3 },
  { word: 'hedgehog', category: 'Animals', difficulty: 3 },
  { word: 'peacock', category: 'Animals', difficulty: 3 },
  { word: 'red panda', category: 'Animals', difficulty: 3 },
  { word: 'otter', category: 'Animals', difficulty: 3 },
  { word: 'meerkat', category: 'Animals', difficulty: 3 },
  { word: 'cheetah', category: 'Animals', difficulty: 3 },
  { word: 'toucan', category: 'Animals', difficulty: 3 },
  { word: 'jellyfish', category: 'Animals', difficulty: 3 },
  { word: 'seahorse', category: 'Animals', difficulty: 3 },
  { word: 'walrus', category: 'Animals', difficulty: 3 },

  // ==========================================
  // --- 8. Delicious Food & Snacks ---
  // ==========================================
  { word: 'pizza', category: 'Food', difficulty: 1 },
  { word: 'hamburger', category: 'Food', difficulty: 1 },
  { word: 'cookie', category: 'Food', difficulty: 1 },
  { word: 'cake', category: 'Food', difficulty: 1 },
  { word: 'donut', category: 'Food', difficulty: 1 },
  { word: 'ice cream', category: 'Food', difficulty: 1 },
  { word: 'popcorn', category: 'Food', difficulty: 1 },
  { word: 'hot dog', category: 'Food', difficulty: 1 },
  { word: 'taco', category: 'Food', difficulty: 1 },
  { word: 'bread', category: 'Food', difficulty: 1 },
  { word: 'cheese', category: 'Food', difficulty: 1 },
  { word: 'egg', category: 'Food', difficulty: 1 },
  { word: 'sandwich', category: 'Food', difficulty: 2 },
  { word: 'sushi', category: 'Food', difficulty: 2 },
  { word: 'pancake', category: 'Food', difficulty: 2 },
  { word: 'french fries', category: 'Food', difficulty: 2 },
  { word: 'chocolate', category: 'Food', difficulty: 2 },
  { word: 'cupcake', category: 'Food', difficulty: 2 },
  { word: 'burrito', category: 'Food', difficulty: 2 },
  { word: 'waffle', category: 'Food', difficulty: 2 },
  { word: 'ramen', category: 'Food', difficulty: 2 },
  { word: 'nachos', category: 'Food', difficulty: 2 },
  { word: 'boba tea', category: 'Food', difficulty: 2 },
  { word: 'spaghetti', category: 'Food', difficulty: 2 },
  { word: 'soup', category: 'Food', difficulty: 2 },
  { word: 'salad', category: 'Food', difficulty: 2 },
  { word: 'lollipop', category: 'Food', difficulty: 2 },
  { word: 'pie', category: 'Food', difficulty: 2 },
  { word: 'croissant', category: 'Food', difficulty: 3 },
  { word: 'cotton candy', category: 'Food', difficulty: 3 },
  { word: 'marshmallow', category: 'Food', difficulty: 3 },
  { word: 'pretzel', category: 'Food', difficulty: 3 },
  { word: 'lasagna', category: 'Food', difficulty: 3 },
  { word: 'fondue', category: 'Food', difficulty: 3 },
  { word: 'dim sum', category: 'Food', difficulty: 3 },

  // ==========================================
  // --- 9. Funny Actions & Memes ---
  // ==========================================
  { word: 'running', category: 'Actions', difficulty: 1 },
  { word: 'jumping', category: 'Actions', difficulty: 1 },
  { word: 'sleeping', category: 'Actions', difficulty: 1 },
  { word: 'eating', category: 'Actions', difficulty: 1 },
  { word: 'dancing', category: 'Actions', difficulty: 1 },
  { word: 'swimming', category: 'Actions', difficulty: 1 },
  { word: 'singing', category: 'Actions', difficulty: 1 },
  { word: 'crying', category: 'Actions', difficulty: 1 },
  { word: 'laughing', category: 'Actions', difficulty: 1 },
  { word: 'flying', category: 'Actions', difficulty: 1 },
  { word: 'reading', category: 'Actions', difficulty: 1 },
  { word: 'cooking', category: 'Actions', difficulty: 1 },
  { word: 'moonwalk', category: 'Actions', difficulty: 2 },
  { word: 'facepalm', category: 'Actions', difficulty: 2 },
  { word: 'dab', category: 'Actions', difficulty: 2 },
  { word: 'karaoke', category: 'Actions', difficulty: 2 },
  { word: 'juggling', category: 'Actions', difficulty: 2 },
  { word: 'photobomb', category: 'Actions', difficulty: 2 },
  { word: 'roller coaster', category: 'Actions', difficulty: 2 },
  { word: 'skateboarding', category: 'Actions', difficulty: 2 },
  { word: 'hugging', category: 'Actions', difficulty: 2 },
  { word: 'climbing', category: 'Actions', difficulty: 2 },
  { word: 'fishing', category: 'Actions', difficulty: 2 },
  { word: 'surfing', category: 'Actions', difficulty: 2 },
  { word: 'skiing', category: 'Actions', difficulty: 2 },
  { word: 'sleepwalking', category: 'Actions', difficulty: 3 },
  { word: 'breakdancing', category: 'Actions', difficulty: 3 },
  { word: 'sneezing', category: 'Actions', difficulty: 3 },
  { word: 'skydive', category: 'Actions', difficulty: 3 },
  { word: 'magic trick', category: 'Actions', difficulty: 3 },
  { word: 'arm wrestling', category: 'Actions', difficulty: 3 },
  { word: 'yawning', category: 'Actions', difficulty: 3 },
  { word: 'somersault', category: 'Actions', difficulty: 3 },

  // ==========================================
  // --- 10. Sci-Fi & Future Tech ---
  // ==========================================
  { word: 'robot', category: 'Sci-Fi', difficulty: 1 },
  { word: 'rocket', category: 'Sci-Fi', difficulty: 1 },
  { word: 'computer', category: 'Sci-Fi', difficulty: 1 },
  { word: 'phone', category: 'Sci-Fi', difficulty: 1 },
  { word: 'drone', category: 'Sci-Fi', difficulty: 2 },
  { word: 'satellite', category: 'Sci-Fi', difficulty: 2 },
  { word: 'laser gun', category: 'Sci-Fi', difficulty: 2 },
  { word: 'vr headset', category: 'Sci-Fi', difficulty: 2 },
  { word: 'ai robot', category: 'Sci-Fi', difficulty: 2 },
  { word: 'flying car', category: 'Sci-Fi', difficulty: 2 },
  { word: 'alien saucer', category: 'Sci-Fi', difficulty: 2 },
  { word: 'space station', category: 'Sci-Fi', difficulty: 2 },
  { word: 'cyborg', category: 'Sci-Fi', difficulty: 2 },
  { word: 'teleporter', category: 'Sci-Fi', difficulty: 3 },
  { word: 'hologram', category: 'Sci-Fi', difficulty: 3 },
  { word: 'jetpack', category: 'Sci-Fi', difficulty: 3 },
  { word: 'time machine', category: 'Sci-Fi', difficulty: 3 },
  { word: 'lightsaber', category: 'Sci-Fi', difficulty: 3 },
  { word: 'portal', category: 'Sci-Fi', difficulty: 3 },
  { word: 'force field', category: 'Sci-Fi', difficulty: 3 },
  { word: 'black hole', category: 'Sci-Fi', difficulty: 3 },
  { word: 'ray gun', category: 'Sci-Fi', difficulty: 3 },

  // ==========================================
  // --- 11. Fantasy & Mythical ---
  // ==========================================
  { word: 'ghost', category: 'Fantasy', difficulty: 1 },
  { word: 'monster', category: 'Fantasy', difficulty: 1 },
  { word: 'alien', category: 'Fantasy', difficulty: 1 },
  { word: 'dragon', category: 'Fantasy', difficulty: 2 },
  { word: 'unicorn', category: 'Fantasy', difficulty: 2 },
  { word: 'wizard', category: 'Fantasy', difficulty: 2 },
  { word: 'witch', category: 'Fantasy', difficulty: 2 },
  { word: 'mermaid', category: 'Fantasy', difficulty: 2 },
  { word: 'zombie', category: 'Fantasy', difficulty: 2 },
  { word: 'vampire', category: 'Fantasy', difficulty: 2 },
  { word: 'fairy', category: 'Fantasy', difficulty: 2 },
  { word: 'genie', category: 'Fantasy', difficulty: 2 },
  { word: 'knight', category: 'Fantasy', difficulty: 2 },
  { word: 'princess', category: 'Fantasy', difficulty: 2 },
  { word: 'werewolf', category: 'Fantasy', difficulty: 3 },
  { word: 'phoenix', category: 'Fantasy', difficulty: 3 },
  { word: 'pegasus', category: 'Fantasy', difficulty: 3 },
  { word: 'centaur', category: 'Fantasy', difficulty: 3 },
  { word: 'cyclops', category: 'Fantasy', difficulty: 3 },
  { word: 'gargoyle', category: 'Fantasy', difficulty: 3 },
  { word: 'magic wand', category: 'Fantasy', difficulty: 2 },
  { word: 'crystal ball', category: 'Fantasy', difficulty: 2 },

  // ==========================================
  // --- 12. Everyday Objects & Tools ---
  // ==========================================
  { word: 'pencil', category: 'Objects', difficulty: 1 },
  { word: 'book', category: 'Objects', difficulty: 1 },
  { word: 'chair', category: 'Objects', difficulty: 1 },
  { word: 'table', category: 'Objects', difficulty: 1 },
  { word: 'clock', category: 'Objects', difficulty: 1 },
  { word: 'key', category: 'Objects', difficulty: 1 },
  { word: 'cup', category: 'Objects', difficulty: 1 },
  { word: 'door', category: 'Objects', difficulty: 1 },
  { word: 'bed', category: 'Objects', difficulty: 1 },
  { word: 'lamp', category: 'Objects', difficulty: 1 },
  { word: 'hat', category: 'Objects', difficulty: 1 },
  { word: 'shoe', category: 'Objects', difficulty: 1 },
  { word: 'umbrella', category: 'Objects', difficulty: 2 },
  { word: 'scissors', category: 'Objects', difficulty: 2 },
  { word: 'glasses', category: 'Objects', difficulty: 2 },
  { word: 'camera', category: 'Objects', difficulty: 2 },
  { word: 'guitar', category: 'Objects', difficulty: 2 },
  { word: 'backpack', category: 'Objects', difficulty: 2 },
  { word: 'hammer', category: 'Objects', difficulty: 2 },
  { word: 'headphones', category: 'Objects', difficulty: 2 },
  { word: 'flashlight', category: 'Objects', difficulty: 2 },
  { word: 'piano', category: 'Objects', difficulty: 2 },
  { word: 'drum', category: 'Objects', difficulty: 2 },
  { word: 'mirror', category: 'Objects', difficulty: 2 },
  { word: 'toothbrush', category: 'Objects', difficulty: 2 },
  { word: 'toilet', category: 'Objects', difficulty: 2 },
  { word: 'pillow', category: 'Objects', difficulty: 2 },
  { word: 'candle', category: 'Objects', difficulty: 2 },
  { word: 'ladder', category: 'Objects', difficulty: 2 },
  { word: 'trophy', category: 'Objects', difficulty: 2 },
  { word: 'telescope', category: 'Objects', difficulty: 3 },
  { word: 'microscope', category: 'Objects', difficulty: 3 },
  { word: 'hourglass', category: 'Objects', difficulty: 3 },
  { word: 'magnifying glass', category: 'Objects', difficulty: 3 },
  { word: 'violin', category: 'Objects', difficulty: 3 },
  { word: 'binoculars', category: 'Objects', difficulty: 3 }
];
